version: '3.8'

services:
  app:
    build:
      context: ../../
      dockerfile: infrastructure/local/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../../:/app
      - app_storage:/app/storage
    env_file:
      - ../../.env
    environment:
      - DEBUG=True
      - LOG_LEVEL=INFO
      - APP_ENV=development
      - DATABASE_URL=sqlite:///./test.db
      - STORAGE_TYPE=local
      - LOCAL_STORAGE_PATH=/app/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    depends_on:
      - ngrok

  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN:-}
    command: http app:8000
    volumes:
      - ngrok_config:/var/lib/ngrok

volumes:
  app_storage:
  ngrok_config: